// <auto-generated />
using System;
using Alphastellar.Case.DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alphastellar.Case.DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alphastellar.Case.CoreLayer.Entities.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Lenght")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Brand1",
                            Color = "Blue",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1778),
                            Lenght = 100,
                            Model = "Model1",
                            Name = "Name1"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Brand2",
                            Color = "Blue",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1779),
                            Lenght = 100,
                            Model = "Model2",
                            Name = "Name2"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Brand3",
                            Color = "Blue",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1780),
                            Lenght = 100,
                            Model = "Model3",
                            Name = "Name3"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Brand4",
                            Color = "Red",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1781),
                            Lenght = 100,
                            Model = "Model4",
                            Name = "Name4"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Brand1",
                            Color = "Blue",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1783),
                            Lenght = 100,
                            Model = "Model1",
                            Name = "Name1"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Brand1",
                            Color = "White",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1784),
                            Lenght = 100,
                            Model = "Model1",
                            Name = "Name1"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Brand1",
                            Color = "Red",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1785),
                            Lenght = 100,
                            Model = "Model1",
                            Name = "Name1"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Brand8",
                            Color = "Black",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1786),
                            Lenght = 100,
                            Model = "Model8",
                            Name = "Name8"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Brand9",
                            Color = "White",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1787),
                            Lenght = 100,
                            Model = "Model9",
                            Name = "Name9"
                        });
                });

            modelBuilder.Entity("Alphastellar.Case.CoreLayer.Entities.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Brand1",
                            Capacity = 100,
                            Color = "Red",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1697),
                            Model = "Model1"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Brand2",
                            Capacity = 100,
                            Color = "Red",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1698),
                            Model = "Model2"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Brand3",
                            Capacity = 100,
                            Color = "Blue",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1699),
                            Model = "Model3"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Brand4",
                            Capacity = 100,
                            Color = "Red",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1700),
                            Model = "Model4"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Brand5",
                            Capacity = 100,
                            Color = "White",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1726),
                            Model = "Model5"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Brand6",
                            Capacity = 100,
                            Color = "Blue",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1727),
                            Model = "Model6"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Brand7",
                            Capacity = 100,
                            Color = "Black",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1728),
                            Model = "Model7"
                        });
                });

            modelBuilder.Entity("Alphastellar.Case.CoreLayer.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Headlights")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Brand1",
                            Color = "Red",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1554),
                            Headlights = false,
                            Model = "Model1",
                            Wheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Brand2",
                            Color = "Red",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1556),
                            Headlights = false,
                            Model = "Model2",
                            Wheels = 4
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Brand3",
                            Color = "Blue",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1558),
                            Headlights = false,
                            Model = "Model3",
                            Wheels = 4
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Brand4",
                            Color = "Blue",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1559),
                            Headlights = false,
                            Model = "Model4",
                            Wheels = 4
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Brand1",
                            Color = "Blue",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1560),
                            Headlights = false,
                            Model = "Model1",
                            Wheels = 4
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Brand1",
                            Color = "Black",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1561),
                            Headlights = false,
                            Model = "Model1",
                            Wheels = 4
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Brand1",
                            Color = "White",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1563),
                            Headlights = false,
                            Model = "Model1",
                            Wheels = 4
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Brand1",
                            Color = "White",
                            CreatedDate = new DateTime(2023, 1, 22, 12, 24, 40, 207, DateTimeKind.Local).AddTicks(1564),
                            Headlights = false,
                            Model = "Model1",
                            Wheels = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
